title: Feedback library
description: >- # this means to ignore newlines until "baseurl:"
  A library of documentation and product feedback user interfaces and workflows.
baseurl: "/feedback-library" # the subpath of your site, e.g. /blog
url: "https://doublegreat.dev" # the base hostname & protocol for your site, e.g. http://example.com

github: double-great/feedback-library

author:
  name: Katy DeCorah

# Build settings
remote_theme: double-great/great-great-jekyll-theme@main
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo
  - jekyll-remote-theme

google_analytics: UA-168677568-1

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - package.json
  - package-lock.json
  - lint
  - CONTRIBUTING.md
  - README.md
  - library.dic
  - node_modules
