title: Feedback library
description: >- # this means to ignore newlines until "baseurl:"
  A library of documentation and product feedback user interfaces and workflows.
baseurl: "/feedback-library" # the subpath of your site, e.g. /blog
url: "https://doublegreat.dev" # the base hostname & protocol for your site, e.g. http://example.com

github: double-great/feedback-library

author:
  name: Katy DeCorah

# Build settings
remote_theme: double-great/great-great-jekyll-theme@main
logo: <svg aria-hidden="true" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="svg-icon"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"></path><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"></path></svg>
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo
  - jekyll-remote-theme

google_analytics: UA-168677568-1

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - package.json
  - package-lock.json
  - lint
  - CONTRIBUTING.md
  - README.md
  - library.dic
  - node_modules
